import { Grid } from '@mui/material';

import type { NextPage } from 'next';
import Head from 'next/head';
import Login from '../components/core/login.component';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  console.log(process.env.NEXTAUTH_URL);
  return (
    <div className={styles.container}>
      <Head>
        <title>Housekeeper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ height: '100vh' }}>
        <Grid
          columns={1}
          container
          height="100%"
          alignItems="center"
          justifyContent="center"
        >
          <Grid item xs>
            <Login />
          </Grid>
        </Grid>
      </main>
    </div>
  );
};

export default Home;
